### ISSUE TITLE
Don't work with special characters.

### ISSUE THREAD

**Issue by zerazobz** [stdunbar/jaxrs-sample#1] opened 2019-02-20 23:22 UTC
If I change the request json to:

`{"description": "The Product Descriptioñ"}`

It will throw `org.codehaus.jackson.JsonParseException: Invalid UTF-8 middle byte 0x22`

> JBWEB000065: HTTP Status 400 - org.codehaus.jackson.JsonParseException: Invalid UTF-8 middle byte 0x22 at [Source: org.jboss.resteasy.core.interception.MessageBodyReaderContextImpl$InputStreamWrapper@555e063b; line: 1, column: 42]

Greetings

**Comment by stdunbar** [comment] 2020-10-05 23:02
After 20 months I'm finally getting back to this.  I can't reproduce this.  I tried Italian and Russian:

16:57:33,624 INFO  [com.hotjoe.services.ProductService] (default task-1) Created product record with description "Questa è una prova delle mie cose"

and

16:59:47,106 INFO  [com.hotjoe.services.ProductService] (default task-1) Created product record with description "Как вас зовут? … зовут Иван"

I'm guessing this is related to the environment.  I'm using Ubuntu 20.04 with LANG set to en_US.UTF-8

**Comment by stdunbar** [comment] 2020-10-13 23:00
I'm going to close this but please reopen if you feel like it's still an issue.

**Closed as completed by stdunbar** 2020-10-13 23:00 UTC
